### ISSUE TITLE
breaks gatsby build with "Invariant Violation: 1"

### ISSUE THREAD

**Issue by barbalex** [apollographql/invariant-packages#5]
When I run `yarn build`:

```
alexa@PCA C:\Users\alexa\ae2
$ yarn build
yarn run v1.15.2
$ gatsby clean && gatsby build
info Deleting .cache, public
info Successfully deleted directories

success open and validate gatsby-configs - 0.144 s
success load plugins - 0.892 s
success onPreInit - 0.073 s
success delete html and css files from previous builds - 0.070 s
success initialize cache - 0.078 s
success copy gatsby files - 0.249 s
success onPreBootstrap - 0.087 s
success source and transform nodes - 0.150 s
success building schema - 0.191 s
success createPages - 0.148 s
success createPagesStatefully - 0.105 s
success onPreExtractQueries - 0.076 s
success update schema - 0.088 s
success extract queries from components - 0.719 s
success write out requires - 0.074 s
success write out redirect data - 0.071 s
success Build manifest and related icons - 0.187 s
success onPostBootstrap - 0.267 s
⠀
info bootstrap finished - 7.380 s
⠀
success run static queries - 0.063 s
success Building production JavaScript and CSS bundles - 58.145 s
success Rewriting compilation hashes - 0.058 s
success run page queries - 0.065 s — 3/3 304.21 queries/second
⠼ Building static HTML for pages
(node:9272) UnhandledPromiseRejectionWarning: MissingAPIError: indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using old Safari versions, make sure to include indexedDB polyfill.
    at Transaction.create (C:\Users\alexa\ae2\public\render-page.js:48507:31)
    at tempTransaction (C:\Users\alexa\ae2\public\render-page.js:47466:23)
    at C:\Users\alexa\ae2\public\render-page.js:47461:61
    at C:\Users\alexa\ae2\public\render-page.js:46976:23
    at callListener (C:\Users\alexa\ae2\public\render-page.js:46659:19)
    at endMicroTickScope (C:\Users\alexa\ae2\public\render-page.js:46746:25)
    at physicalTick (C:\Users\alexa\ae2\public\render-page.js:46721:30)
(node:9272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

 ERROR #95313

Building static HTML failed for path "/offline-plugin-app-shell-fallback/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  10 |     function InvariantError(message) {
  11 |         if (message === void 0) { message = genericMessage; }
> 12 |         var _this = _super.call(this, typeof message === "number"
     | ^
  13 |             ? genericMessage + ": " + message + " (see https://github.com/apollographql/invariant-packages)"
  14 |             : message) || this;
  15 |         _this.framesToPop = 1;


  WebpackError: Invariant Violation: Invariant Violation: 1 (see https://github.com/apollographql/invariant-packages)

  - invariant.esm.js:12 new InvariantError
    node_modules/ts-invariant/lib/invariant.esm.js:12:1

  - bundle.esm.js:64 checkFetcher
    node_modules/apollo-link-http-common/lib/bundle.esm.js:64:52

  - bundle.esm.js:11 new BatchHttpLink
    node_modules/apollo-link-batch-http/lib/bundle.esm.js:11:21

  - client.js:59 ./src/client.js.__webpack_exports__.default
    src/client.js:59:25

  - App.js:32 App
    src/App.js:32:27


⠼ Building static HTML for pages
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This package exists because:
```
alexa@PCA C:\Users\alexa\ae2
$ yarn why ts-invariant
yarn why v1.15.2
[1/4] Why do we have the module "ts-invariant"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "ts-invariant@0.4.4"
info Reasons this module exists
   - "apollo-cache-inmemory" depends on it
   - Hoisted from "apollo-cache-inmemory#ts-invariant"
   - Hoisted from "apollo-client#ts-invariant"
   - Hoisted from "apollo-link#ts-invariant"
   - Hoisted from "@apollo#react-hooks#ts-invariant"
   - Hoisted from "apollo-link-batch-http#apollo-link-http-common#ts-invariant"
   - Hoisted from "apollo-client#apollo-utilities#ts-invariant"
   - Hoisted from "@apollo#react-hooks#@apollo#react-common#ts-invariant"
info Disk size without dependencies: "48KB"
info Disk size with unique dependencies: "108KB"
info Disk size with transitive dependencies: "108KB"
info Number of shared dependencies: 1
Done in 0.94s.
```

Seems related to https://github.com/apollographql/invariant-packages/issues/2

The weird thing is: I have another gatsby project using apollo and thus ts-invariant. Also v0.4.4. This does not happen there.

What I have tried to do:
- `del yarn.lock && rmdir /s node_modules && yarn cache clean && yarn && yarn build`: still happens
- building on my notebook with macOS Mojave: exact same error

My project: https://github.com/FNSKtZH/ae2

Versions:
- Windows 10 and macOS Mojave
- node v11.13.0 and v11.10.1
- more here: https://github.com/FNSKtZH/ae2/blob/master/package.json

**Comment by barbalex** [comment]
I tried to force using v0.4.3 by installing it and adding it as resolution in package.json. Issue remains :-(

**Comment by barbalex** [comment]
Is there a way to not use ts-invariant as I do not use typescript?

**Comment by barbalex** [comment]
I tried all Versions down to 0.3.3. All cause the issue. Seems that I would have to remove apollo from the project to be able to create builds :-(

**Comment by barbalex** [comment]
O.k., got it: Above the errors mentioning ts-invariant was mentioned: `indexedDB API not found`. I am actually creating an indexed-db which does not work in gatsby build. Sorry for the noise.

**Comment by barbalex** [comment]
Nope: Initiating the indexed-db _was_ bad. But after removing that this error remains:

```
alexa@PCA C:\Users\alexa\ae2
$ yarn build
yarn run v1.15.2
$ gatsby clean && gatsby build
info Deleting .cache, public
info Successfully deleted directories

success open and validate gatsby-configs - 0.110 s
success load plugins - 0.679 s
success onPreInit - 0.071 s
success delete html and css files from previous builds - 0.063 s
success initialize cache - 0.058 s
success copy gatsby files - 0.142 s
success onPreBootstrap - 0.065 s
success source and transform nodes - 0.169 s
success building schema - 0.166 s
success createPages - 0.073 s
success createPagesStatefully - 0.087 s
success onPreExtractQueries - 0.060 s
success update schema - 0.070 s
success extract queries from components - 0.710 s
success write out requires - 0.059 s
success write out redirect data - 0.058 s
success Build manifest and related icons - 0.150 s
success onPostBootstrap - 0.222 s
⠀
info bootstrap finished - 6.101 s
⠀
success run static queries - 0.055 s
success Building production JavaScript and CSS bundles - 42.259 s
success Rewriting compilation hashes - 0.067 s
success run page queries - 0.068 s — 3/3 286.26 queries/second

 ERROR #95313

Building static HTML failed for path "/offline-plugin-app-shell-fallback/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  10 |     function InvariantError(message) {
  11 |         if (message === void 0) { message = genericMessage; }
> 12 |         var _this = _super.call(this, typeof message === "number"
     | ^
  13 |             ? genericMessage + ": " + message + " (see https://github.com/apollographql/invariant-packages)"
  14 |             : message) || this;
  15 |         _this.framesToPop = 1;


  WebpackError: Invariant Violation: Invariant Violation: 1 (see https://github.com/apollographql/invariant-packages)

  - invariant.esm.js:12 new InvariantError
    node_modules/ts-invariant/lib/invariant.esm.js:12:1

  - bundle.esm.js:64 checkFetcher
    node_modules/apollo-link-http-common/lib/bundle.esm.js:64:52

  - bundle.esm.js:11 new BatchHttpLink
    node_modules/apollo-link-batch-http/lib/bundle.esm.js:11:21

  - client.js:59 ./src/client.js.__webpack_exports__.default
    src/client.js:59:25

  - App.js:32 App
    src/App.js:32:27


⠹ Building static HTML for pages
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by saitodisse** [comment]
> I tried all Versions down to 0.3.3. All cause the issue. Seems that I would have to remove apollo from the project to be able to create builds :-(

Same error here, but I got `Invariant Violation: 2`

**Comment by saitodisse** [comment]
maybe this helps: https://github.com/gatsbyjs/gatsby/issues/11225#issuecomment-457211628

**Comment by saitodisse** [comment]
> maybe this helps: [gatsbyjs/gatsby#11225 (comment)](https://github.com/gatsbyjs/gatsby/issues/11225#issuecomment-457211628)

Just worked. Use `isomorphic-fetch` and the `gatsby-ssr.js`

**Comment by barbalex** [comment]
@saitodisse thanks A LOT for finding this! Solved it for me too.

**Comment by desmondpnw3dev** [comment]
None of the solutions I found for days worked until I found this:

The `gatsby-plugin-apollo` did the trick for me: `npm install gatsby-plugin-apollo @apollo/client`.
```
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-apollo',
      options: {
        uri: 'https://example.com/graphql'
      }
    }
  ]
};
```

https://www.gatsbyjs.com/plugins/gatsby-plugin-apollo/#gatsby-plugin-apollo

I hope this helps anyone else currently experiencing this issue!

**Comment by anthonwellsjo** [comment]
Oh man desmondpnw3dev you just saved my ass

**Comment by dinhanhthi** [comment]
Coming with desmondpnw3dev's solution, you may need to install the 'graphql' version that matches the graphql version of gatsby (check this with `npm list graphql`). It works for me!
